server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host:
  rabbitmq:
    host:
    virtual-host: /mall
    username: mall
    password: mall
    template:
      exchange: MALL.SMS.EXCHANGE # 这里定义了交换机，就不用再在代码中指定了
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.mall.user.pojo
