server:
  port: 10010
spring:
  application:
    name: mall-gateway
  cloud:
    refresh:
      refreshable: none  #不加入会造成循环依赖?
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  ignored-services:
    - upload-service  # 忽略upload-service服务
  add-host-header: true
  sensitive-headers: #覆盖默认敏感信息
  host:
    connect-timeout-millis: 60000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

