server:
  port: 10086
spring:
  application:
    name: mall-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false # 不会显示自己
    fetch-registry: false # 不去拉取自己服务
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 10000 # 每隔 10 秒进行一次服务列表清理
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000 # 熔断超时时长：10000ms

